implement a fuller calculation
uisautomation/pidash-ucamstaffoncosts pull request #9
Opened 2018-06-12 16:16 UTC by rjw57

This PR implements a fuller calculation of on-costs. It is *highly* recommended that you read the accompanying documentation for this PR as it is quite in-depth.

Closes #7.

2018-06-13 08:12 UTC, rjw57 commented
The documentation has now been built by CircleCI at https://43-133829605-gh.circle-artifacts.com/0/doc/index.html

2018-06-14 13:28 UTC, abrahammartin requested changes

2018-06-14 13:28 UTC, abrahammartin commented on ucamstaffoncosts/salary/scales.py
> +    #: Grade 11
Typo

2018-06-14 13:28 UTC, abrahammartin commented on ucamstaffoncosts/salary/scales.py
> +    #: Grade 11
Typo

2018-06-14 13:28 UTC, abrahammartin commented on ucamstaffoncosts/salary/scales.py
> +    #: Grade 11
Typo

2018-06-14 13:28 UTC, abrahammartin commented on ucamstaffoncosts/salary/scales.py
> +    #: Grade 11
Typo

2018-06-14 13:28 UTC, abrahammartin commented on ucamstaffoncosts/costs.py
> +
we need to add MRC Pension (fixed at 15.9%)

2018-06-14 14:34 UTC, rjw57 commented on ucamstaffoncosts/costs.py
> +
I'll move this to #6 since I think it makes sense to address it there.

2018-06-15 12:29 UTC, abrahammartin approved these changes

2018-06-15 13:07 UTC, merged